# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Store.destroy_all
Instrument.destroy_all

s1 = Store.create(name: "Sound Swap", hours: "9am - 7pm")

Instrument.create(name: "Squier by Fender Affinity Series Jazzmaster", description: "Offset body classic for students and those looking for an affordable version of a stylistic classic guitar *Three-way toggle pickup switch*", daily_rate: 5, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2251.png", category: "guitars")
Instrument.create(name: "Squier by Fender Classic-Vibe 60's Mustang", description: "Faithful and Affordable Mustang Inspired by 1960s-era models with a slim profile and nickel-plated hardware", daily_rate: 9, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2978.png", category: "guitars")
Instrument.create(name: "Fender Player Series Left-Handed Telecaster", description: "Left handed workhorse Telecaster with gloss finish and Two Player Series single-coil Telecaster pickup", daily_rate: 14, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2813.png", category: "guitars")
Instrument.create(name: "Fender Signature Jimmy Vaughn 'Tex-Mex Strat'", description: "Texas artist Jimmie Vaughn's signature model with master volume and 2 tone controls", daily_rate: 20, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-1354.png", category: "guitars")
Instrument.create(name: "Fender American Professional Series Telecaster Deluxe", description: "American Professional Series Tele Deluxe with two Tim Shaw-designed ShawBucker humbucking pickups", daily_rate: 40, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2256.png", category: "guitars")
Instrument.create(name: "Fender Parlor Size Acoustic Guitar (CP-60S)", description: "Solid spruce top with scalloped 'X'-bracing provides warm and chimey tone, and gets even sweeter with age", daily_rate: 6, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2534.png", category: "guitars")
Instrument.create(name: "Fender Newporter Dreadnought 12-String Cutaway Acoustic Guitar with Electronics", description: "Fishman® Isys™ III pickup system with active preamp, tuner, volume and tone controls", daily_rate: 10, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2875.png", category: "guitars")
Instrument.create(name: "Seagull Maritime Series Solidwood High Gloss Mahogany Top Acoustic Guitar with Electronics", description: "Tapered headstock, dual-function truss rods and Quantum I electronics deliver great plugged-in tone via an undersaddle pickup", daily_rate: 13, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-1457.png", category: "guitars")
Instrument.create(name: "Gretsch Synchromatic Cutaway Acoustic Guitar with Electronics", description: "The Chromatic Bridge and Tailpiece provide balanced string tension and enhanced bass response", daily_rate: 19, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2373.png", category: "guitars")

Instrument.create(name: "Squier by Fender Bronco Short-Scale Bass", description: "30 in scale length C-shape maple neck with 9.5 in radius maple fingerboard and 19 medium jumbo frets (Short Scale - Great for Learning)", daily_rate: 5, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-1397.png", category: "basses")
Instrument.create(name: "Gretsch Electromatic Junior Jet Bass II", description: "30.3in short scale length for maximum playability Rosewood fretboard has a 12in radius, flatter than most short scale basses", daily_rate: 8, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2205.png", category: "basses")
Instrument.create(name: "Fender Standard Jazz Bass Pau Ferro", description: "Classic Electric Bass with Pau Ferro fingerboard and dual single coil Jazz Bass pickups to provide the tried and true sound that they are famous for", daily_rate: 14, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2744.png", category: "basses")
Instrument.create(name: "Supro Huntington I Vintage Styled Short-Scale Bass ", description: "Classic body shape of the early ‘60s Supro Ozark model with vintage-correct passive electronics and sonic inspiration from the Supro Pocket Bass", daily_rate: 20, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2945.png", category: "basses")
Instrument.create(name: "Fender American Performer Series Precision Bass ", description: "Fender's Greasebucket master tone circuit rolls off highs without reducing gain also includes middle pickup volume control and bridge pickup volume control", daily_rate: 40, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2833.png", category: "basses")

Instrument.create(name: "Mapex Storm Poplar 5 Piece Drum Kit", description: "The 5-Piece Rock Kit includes 10in and 12in bass-mounted rack toms, a 14in snare drum, and a 22in bass drum. The smaller and shallower rack toms make placement easier and overall set-up more comfortable while the large floor tom delivers a big sound.", daily_rate: 17, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2608.png", category: "drums")
Instrument.create(name: "PDP Concept Classic Maple 'Bop' Drum Kit ", description: "Inspired by Traditional Bop-Era Drum Sets, includes 8in x 12in Tom, 14in x 14in Floor Tom and a 14in x 18in Bass Drum", daily_rate: 31, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2856.png", category: "drums")
Instrument.create(name: "Mapex Saturn Maple OR Walnut 4 Piece Pro Kit", description: "Maple and walnut hybrid shell drum kit consists of 3 Saturn V Drum Shells (Kick Drum, Floor Tom and Rack Tom), with a Black Panther Snare Drum", daily_rate: 44, _id: s1.id, image_url:"", category: "drums")
Instrument.create(name: "Mapex BLACKPANTHER Black Panther Custom Snare", description: "Upgrade your drum kit with a distinctive to the ear and eye- Black Panther snare", daily_rate: 9, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2100.png", category: "drums")
Instrument.create(name: "Lp Matador Wood Bongos w/stand", description: "Natural finish, 5/16in diameter tuning lugs, steel backing plate and plated cast aluminum bottoms- includes a tuning wrench", daily_rate: 7, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2115.png", category: "drums")
Instrument.create(name: "Roland EC-10 Electroic Layered Hybrid Acoustic/Electronic Cajon", description: "Versatile selection of acoustic and electronic percussion sounds to support a wide range of music styles. Also includes studio-optimized cajon sounds to enhance the instrument’s acoustic sound, providing additional depth and punch while performing", daily_rate: 11, _id: s1.id, image_url:"https://rocknrollrentals.com/images/product/medium/ae00-2262.png", category: "drums")